### ISSUE TITLE
Units are not generated

### ISSUE THREAD

**Issue by messi1** [OPCFoundation/UA-ModelCompiler#45]
Hi 
I tried to create an EUInformation property. It seems to me that either I did a mistake or the compiler is not generating the code for the Units not correctly.
In case I did something wrong, it would be great to add an example to the existing models.

It tested it with the following snippet:
```               
 <opc:Variable SymbolicName="SetPoint1" DataType="ua:Double" AccessLevel="ReadWrite" Historizing="true" TypeDefinition="ua:BaseVariableType" WriteAccess="0">
   <opc:Children>
     <opc:Property SymbolicName="ua:EngineeringUnits" DataType="ua:EUInformation" ModellingRule="Mandatory">
        <opc:Fields>
          <opc:Field Name="ua:NamespaceUri" DataType="tns:String">http://www.opcfoundation.org/UA/units/un/cefact</opc:Field>
          <opc:Field Name="ua:UnitId" DataType="tns:String" Value="4408652">4408652</opc:Field>
          <opc:Field Name="ua:DisplayName" DataType="tns:String">°C</opc:Field>
        </opc:Fields>
     </opc:Property>
   </opc:Children>
 </opc:Variable>
```

**Comment by benkinooby** [comment]
Hi,
what revision of UA-ModelCompiler are you using?

I had issues with running UA-ModelCompiler from branch master because of https://github.com/OPCFoundation/UA-ModelCompiler/issues/46 , therefore I checked out v1.04.

v1.04 worked fine, until I tried to use EUInformation. I noticed that v.104 was released 2018-03-17 but Engineering Units were reworked in commit e53084ac1a2d1c95d0c54474862c800271fb979f 

Check out master and follow the advice given in https://github.com/OPCFoundation/UA-ModelCompiler/issues/46#issuecomment-603875272 to compile your ModelDesign. At least, that worked for me.

Be sure to test the resulting UANodeSet with your OPC UA stack as well!

**Comment by opcfoundation-org** [comment]
The declaration is wrong. You need to declare a DefaultValue like:

```
opc:Property SymbolicName="TrueState" DataType="ua:LocalizedText" ModellingRule="Optional">
            <opc:DefaultValue>
              <uax:LocalizedText>
                <uax:Locale>en</uax:Locale>
                <uax:Text>Enabled</uax:Text>
              </uax:LocalizedText>
            </opc:DefaultValue>
</opc:Property>
```
