### ISSUE TITLE
Cant Compile Models using UANodeSet.xsd schema

### ISSUE THREAD

**Issue by candyman485** [OPCFoundation/UA-ModelCompiler#5]
Hello,

I want to generate C# source files with the ModelCompiler out of an InformationModel that was compiled as .xml using the UANodeSet.xsd. According to the description the ModelCompiler should be able to do that.

Following the instructions and the help file to generate the files, I get the follow Exception:

![modelcompilerexception](https://cloud.githubusercontent.com/assets/19670434/17802508/faa2ecdc-65f0-11e6-9f25-6f9da77f490b.png)

The XML file starts like this:

![informationmodel](https://cloud.githubusercontent.com/assets/19670434/17802615/846dd33c-65f1-11e6-9fec-af649f796b94.png)

I marked the line, that causes the Exception. 

Did I miss something? 

I would appreciate any help on this.

Thanks in advance!
Best regards

**Comment by SparhawkSoftware** [comment]
The [README](https://github.com/OPCFoundation/UA-ModelCompiler/blob/master/README.md) has been fixed.
This should address your concerns.

**Comment by ggokka** [comment]
Have you found a solution?

**Comment by SparhawkSoftware** [comment]
The README states:

> The input format for the tool is a file that conforms to the schema defined in UA Model Design.xsd.

The UANodeSet.xsd is an OUTPUT of the tool. Not the input.

**Comment by Hanky27** [comment]
And how can one create/edit the input xml files in UA Model Design.xsd format?

**Comment by mpostol** [comment]
@Hanky27 you can use for example CAS Address Space Model Designer. The procedure of how to design and maintain UA Information Model and the Address Space content description is covered by the document:

[OPC UA Information Model Deployment](http://www.commsvr.com/InternetDSL/commserver/P_DowloadCenter/P_Publications/20140301E_DeploymentInformationModel.pdf)

My concern is that the xml file compliant with UA Model Design.xsd is a good Information Model representation for machines processing only because it is xml file. To describe our reality, e.g. process under control, we should use human-centric languages.  Many years ago I proposed UA Working Group to work on it but it was not accepted. So today UAModelDesign schema is the only not official UA Information Model representation. UANodSet is described in the specification (I believe part 6 Mapping ) and is required. 

> NOTE:  as @randy-armstrong said it is the output of the cop[iler. Unfortunately, it is defined in the specification, but the source is not. 

Because this problem is vital for my project [Object-Oriented Internet](https://github.com/mpostol/OPC-UA-OOI) I will appreciate any feedback, suggestions, and your requirements.

Anyway, I believe that the tools we have today are not well prepared for the design time UA Information Model share and maintain.  Of course here the question arises about the trade-off between the specification and commercial tooling role.  It leads to the typical egg-chicken problem: the users need a solution, but the vendors need a business scope. 

Hope it helps.
